#!/bin/bash

############################ INPUT ###############################
cpus=20
queue=short
som=som2
###############
location=som2
mass_criteria=m200
min_mass=2e12
max_mass=2e15

N_par=1000000 #only when computing the CDM/NU correlation function
random_points=10000000 #number of points in the random catalogue

random_file=/disk/disksom2/villa/Correlation_function/Random_catalogue/random_catalogue_1e7.dat

DD_action=compute
RR_action=read
DR_action=compute

DD_name=DD.dat
DR_name=DR.dat

BoxSize=500.0
bins=40


################# 0.0 eV ##################
Mnu=0.0

Rmin=0.1
Rmax=50.0
RR_name=RR_0.1_50_40_1e7.dat

####### z=0.0 #######
z=0.0

mode=halos
f_out=TPCF_halos_0.0_z=0.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.0_z=0.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=0.5 #######
z=0.5

mode=halos
f_out=TPCF_halos_0.0_z=0.5.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.0_z=0.5.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=1.0 #######
z=1.0

mode=halos
f_out=TPCF_halos_0.0_z=1.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.0_z=1.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=2.0 #######
z=2.0

mode=halos
f_out=TPCF_halos_0.0_z=2.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.0_z=2.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out



################# 0.3 eV ##################
Mnu=0.3

Rmin=0.103
Rmax=51.5
RR_name=RR_0.103_51.5_40_1e7.dat

####### z=0.0 #######
z=0.0

mode=halos
f_out=TPCF_halos_0.3_z=0.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.3_z=0.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=0.5 #######
z=0.5

mode=halos
f_out=TPCF_halos_0.3_z=0.5.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.3_z=0.5.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=1.0 #######
z=1.0

mode=halos
f_out=TPCF_halos_0.3_z=1.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.3_z=1.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=2.0 #######
z=2.0

mode=halos
f_out=TPCF_halos_0.3_z=2.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.3_z=2.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out


################# 0.6 eV ##################
Mnu=0.6

Rmin=0.106
Rmax=53.0
RR_name=RR_0.106_53_40_1e7.dat

####### z=0.0 #######
z=0.0

mode=halos
f_out=TPCF_halos_0.6_z=0.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.6_z=0.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=0.5 #######
z=0.5

mode=halos
f_out=TPCF_halos_0.6_z=0.5.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.6_z=0.5.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=1.0 #######
z=1.0

mode=halos
f_out=TPCF_halos_0.6_z=1.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.6_z=1.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

####### z=2.0 #######
z=2.0

mode=halos
f_out=TPCF_halos_0.6_z=2.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out

mode=subhalos
f_out=TPCF_subhalos_0.6_z=2.dat

clusterlauncher -q $queue -n $cpus python correlation_function.py $Mnu $z $location $mass_criteria $min_mass $max_mass $mode $N_par $random_points $DD_action $RR_action $DR_action $DD_name $RR_name $DR_name $random_file $BoxSize $bins $Rmin $Rmax $f_out