#!/bin/bash
#This script is used to generate the P(k) of the CDM, NU, DM and halos from the
#new simulations run by Paco: 1000 Mpc/h 768^3 CDM particles using the
#Yacine-Bird code

dims=1024

mass_interval=1
min_mass=5.0e2
max_mass=3.0e5


############################## CDM ###################################

######## z=0 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/CDM/snapdir_003/snap_003
groups_fname=/data2/home/villa/Yacine_Bird/CDM
groups_number=3

f_CDM=Pk_DM_0.0_z=0.dat
f_NU=A
f_DM=A
f_CDM_NU=A 
f_halos=Pk_halos_0.0_z=0.dat
f_CDM_halos=Pk_DM-halos_0.0_z=0.dat
f_DM_halos=A

obj=CDM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=CDM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######## z=0.5 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/CDM/snapdir_002/snap_002
groups_fname=/data2/home/villa/Yacine_Bird/CDM
groups_number=2

f_CDM=Pk_DM_0.0_z=0.5.dat
f_NU=A
f_DM=A
f_CDM_NU=A
f_halos=Pk_halos_0.0_z=0.5.dat
f_CDM_halos=Pk_DM-halos_0.0_z=0.5.dat
f_DM_halos=A

obj=CDM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=CDM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######## z=1 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/CDM/snapdir_001/snap_001
groups_fname=/data2/home/villa/Yacine_Bird/CDM
groups_number=1

f_CDM=Pk_DM_0.0_z=1.dat
f_NU=A
f_DM=A
f_CDM_NU=A
f_halos=Pk_halos_0.0_z=1.dat
f_CDM_halos=Pk_DM-halos_0.0_z=1.dat
f_DM_halos=A

obj=CDM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=CDM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######## z=2 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/CDM/snapdir_000/snap_000
groups_fname=/data2/home/villa/Yacine_Bird/CDM
groups_number=0

f_CDM=Pk_DM_0.0_z=2.dat
f_NU=A
f_DM=A
f_CDM_NU=A
f_halos=Pk_halos_0.0_z=2.dat
f_CDM_halos=Pk_DM-halos_0.0_z=2.dat
f_DM_halos=A

obj=CDM

python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=CDM-halos

python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######################################################################



############################## NU0.6 ###################################

######## z=0 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/NU0.6/snapdir_003/snap_003
groups_fname=/data2/home/villa/Yacine_Bird/NU0.6
groups_number=3

f_CDM=Pk_CDM_0.6_z=0.dat
f_NU=Pk_NU_0.6_z=0.dat
f_DM=Pk_DM_0.6_z=0.dat
f_CDM_NU=Pk_CDM-NU_0.6_z=0.dat
f_halos=Pk_halos_0.6_z=0.dat
f_CDM_halos=A
f_DM_halos=Pk_DM-halos_0.6_z=0.dat

obj=DM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=DM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######## z=0.5 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/NU0.6/snapdir_002/snap_002
groups_fname=/data2/home/villa/Yacine_Bird/NU0.6
groups_number=2

f_CDM=Pk_CDM_0.6_z=0.5.dat
f_NU=Pk_NU_0.6_z=0.5.dat
f_DM=Pk_DM_0.6_z=0.5.dat
f_CDM_NU=Pk_CDM-NU_0.6_z=0.5.dat
f_halos=Pk_halos_0.6_z=0.5.dat
f_CDM_halos=A
f_DM_halos=Pk_DM-halos_0.6_z=0.5.dat

obj=DM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=DM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######## z=1 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/NU0.6/snapdir_001/snap_001
groups_fname=/data2/home/villa/Yacine_Bird/NU0.6
groups_number=1

f_CDM=Pk_CDM_0.6_z=1.dat
f_NU=Pk_NU_0.6_z=1.dat
f_DM=Pk_DM_0.6_z=1.dat
f_CDM_NU=Pk_CDM-NU_0.6_z=1.dat
f_halos=Pk_halos_0.6_z=1.dat
f_CDM_halos=A
f_DM_halos=Pk_DM-halos_0.6_z=1.dat

obj=DM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=DM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

######## z=2 ########
snapshot_fname=/data2/home/villa/Yacine_Bird/NU0.6/snapdir_000/snap_000
groups_fname=/data2/home/villa/Yacine_Bird/NU0.6
groups_number=0

f_CDM=Pk_CDM_0.6_z=2.dat
f_NU=Pk_NU_0.6_z=2.dat
f_DM=Pk_DM_0.6_z=2.dat
f_CDM_NU=Pk_CDM-NU_0.6_z=2.dat
f_halos=Pk_halos_0.6_z=2.dat
f_CDM_halos=A
f_DM_halos=Pk_DM-halos_0.6_z=2.dat

obj=DM

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos

obj=DM-halos

#python Pk.py $snapshot_fname $groups_fname $groups_number $obj $mass_interval $min_mass $max_mass $dims $f_CDM $f_NU $f_DM $f_CDM_NU $f_halos $f_CDM_halos $f_DM_halos
######################################################################

